version: '3.7'

services:
  tf:
    image: hashicorp/terraform:1.3.6
    volumes:
      - .:/infra
    
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SESSION_TOKE=${AWS_SESSION_TOKE}
     